# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WQAlertDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'WQViewFrame', '~> 0.1.0’
  # Pods for WQAlertDemo

  target 'WQAlertDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WQAlertDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
